# Generated by Django 4.2.2 on 2023-06-30 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bacheca", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bestemmiabacheca",
            options={"verbose_name_plural": "Bestemmie bacheca"},
        ),
        migrations.AlterField(
            model_name="bestemmiabacheca",
            name="data_bestemmia",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
